services:
  postgres:
    image: 'postgres:16.2'
    container_name: water-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - '${POSTGRES_PORT}:5432'
