server:
  servlet:
    context-path: /api/v1
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: water-gas

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    locations: 'db/migration'
    table: 'migrations_core'
    default-schema: 'core'
    validate-on-migrate: false